name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check format
        run: npm format:check
      - name: Check lint
        run: npm lint:check
      - name: Run tests
        run: npm test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
